# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
podfile: Example/Podfile
before_install:
#- pod install --no-repo-update --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/MissingAnchors.xcworkspace -scheme MissingAnchors-Example -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
